{
 "title": "ADK LLM stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Approx cost (Gemini Flash 2.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "adk_approx_cost_total", "legendFormat": "{{agent_name}}" }
   ]
  },
  {
   "title": "Number of LLM calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "adk_llm_calls_total{job=\"adk_job\"}",
     "legendFormat": "{{agent_name}}"
    }
   ]
  },
  { "title": "Total tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total input tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "adk_input_tokens_total{job=\"adk_job\"}",
     "legendFormat": "{{agent_name}}"
    }
   ]
  },
  {
   "title": "Total cached tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "adk_cached_tokens_total", "legendFormat": "{{agent_name}}" }
   ]
  },
  {
   "title": "Total output tokens ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "adk_output_tokens_total{job=\"adk_job\"}",
     "legendFormat": "{{agent_name}}"
    }
   ]
  },
  {
   "title": "Total thoughts tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "adk_thoughts_tokens_total", "legendFormat": "{{agent_name}}" }
   ]
  },
  { "title": "Last call tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Last input tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "adk_last_input_tokens{job=\"adk_job\"}",
     "legendFormat": "{{agent_name}}"
    }
   ]
  },
  {
   "title": "Last call cached tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "adk_last_cached_tokens{job=\"adk_job\"}",
     "legendFormat": "{{agent_name}}"
    }
   ]
  },
  {
   "title": "Last output tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "adk_last_output_tokens{job=\"adk_job\"}",
     "legendFormat": "{{agent_name}}"
    }
   ]
  },
  {
   "title": "Last call thoughts tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "adk_last_thoughts_tokens{job=\"adk_job\"}",
     "legendFormat": "{{agent_name}}"
    }
   ]
  }
 ]
}